version: "2.1"

services:
      
  zookeeper:
    image: zookeeper:3.4.10
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:0.11.0.1
    container_name: kafka
    ports:
      - "9092:9092"
    links:
      - zookeeper:zookeeper
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    volumes:
      - "./kafka/server.properties:/opt/kafka/config/server.properties"

  jobmanager:
    image: ecg/flink_1.4.0-prometheus-hadoop28-scala_2.11
    container_name: jobmanager
    ports:
      - "6123"
      - "8081:8081"
    links:
      - kafka:kafka
    command: jobmanager
    privileged: true
    volumes:
      - "./flink/flink-conf.yaml:/opt/flink/conf/flink-conf.yaml"
      - "./flink/log4j.properties:/opt/flink/conf/log4j.properties"
      - "./target:/app"
      - "./heapdumps:/heapdumps"

  taskmanager:
    image: ecg/flink_1.4.0-prometheus-hadoop28-scala_2.11
    expose:
      - "6121"
      - "6122"
    links:
      - kafka:kafka
      - jobmanager:jobmanager
    command: taskmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    privileged: true
    volumes:
      - "./flink/flink-conf.yaml:/opt/flink/conf/flink-conf.yaml"
      - "./flink/log4j.properties:/opt/flink/conf/log4j.properties"
      - "./target:/app"
      - "./heapdumps:/heapdumps"